DEPTH_WIDTH = 640
DEPTH_HEIGHT = 480
COLOR_WIDTH = 640
COLOR_HEIGHT = 480
FPS = 30

MIN_DEPTH_M = 0.25
MAX_DEPTH_M = 2.0
POINT_STRIDE = 2
VOXEL_SIZE_M = 0.01

USE_ICP = False
ICP_MAX_CORRESPONDENCE_DISTANCE_M = 0.05
AUTO_ACCUMULATE_EVERY_N_FRAMES = 15

OUTPUT_DIR = "output"
DEMO_MODE = False
